version: '3'
services:
  apache:
    image: adji21/moodleswarm
    networks:
      - db
      - dockertraefik_pub
    volumes:
      - moodle_data:/var/www/moodledata:rw

  db:
    image: 'mysql:5.7'
    volumes:
      - moodle_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: r00t
    networks:
      - db

networks:
  db:
    internal: true
  dockertraefik_pub:
    external: true

volumes:
  moodle_data:
  moodle_db:
