version: '3'
services:
  apache:
    image: adji21/moodleswarm
    networks:
      - db
    ports:
      - 80:8080
    volumes:
      - moodle_data:/var/www/moodledata

  db:
    image: 'mysql:5.7'
    volumes:
      - moodle_db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: r00t
    networks:
      - db

networks:
  db:
    internal: true

volumes:
  moodle_data:
  moodle_db:
